// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace migrations.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20210919182143_addAnalysis")]
    partial class addAnalysis
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CatClinic", b =>
                {
                    b.Property<int>("CatsId")
                        .HasColumnType("integer");

                    b.Property<int>("ClinicsId")
                        .HasColumnType("integer");

                    b.HasKey("CatsId", "ClinicsId");

                    b.HasIndex("ClinicsId");

                    b.ToTable("CatClinic");
                });

            modelBuilder.Entity("DataLayer.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ClinicId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<DateTime>("dateOfAnalysis")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("PatientId");

                    b.ToTable("Analysis");
                });

            modelBuilder.Entity("DataLayer.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Feed")
                        .HasColumnType("text");

                    b.Property<bool>("HasCirtificate")
                        .HasColumnType("boolean");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<double>("Weigth")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Cats");
                });

            modelBuilder.Entity("DataLayer.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("CatClinic", b =>
                {
                    b.HasOne("DataLayer.Cat", null)
                        .WithMany()
                        .HasForeignKey("CatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Clinic", null)
                        .WithMany()
                        .HasForeignKey("ClinicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Analysis", b =>
                {
                    b.HasOne("DataLayer.Clinic", "Clinic")
                        .WithMany("Analyzes")
                        .HasForeignKey("ClinicId");

                    b.HasOne("DataLayer.Cat", "Patient")
                        .WithMany("Analyzes")
                        .HasForeignKey("PatientId");

                    b.Navigation("Clinic");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DataLayer.Cat", b =>
                {
                    b.Navigation("Analyzes");
                });

            modelBuilder.Entity("DataLayer.Clinic", b =>
                {
                    b.Navigation("Analyzes");
                });
#pragma warning restore 612, 618
        }
    }
}
